GET http://localhost:3000/todos/?status=NOT%20DONE
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
    "todo": "Buy a Dog"
}

###

GET http://localhost:3000/agenda/?date=2021-12-12