GET http://localhost:3000/todos/?status=NOT%20DONE
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
    "todo": "Buy a Dog"
}

###

GET http://localhost:3000/agenda/?date=2021-12-12

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id": 100,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}